#!/bin/bash

## Syntax: briefcase_symlink [source] [destination]
function briefcase_symlink
{
  if [ ! -d $1 ] && [ ! -f $1 ]; then
    echo "Error, the source ($1) does not exists"
    return
  fi

  if [ ! "$(readlink $2)" = "$1" ]; then
    if [ -d $2 ] || [ -f $2 ]; then
      echo "Warning! The destination file or folder already exists"
      echo "Moving $2 to $HOME/.dotfiles/briefcase/backup"
      read -p "Continue? (y/N)"
      [[ ! $REPLY =~ ^[Yy]$ ]] && return
      mv $2 $HOME/.dotfiles/briefcase/backup
    fi
   ln -s $1 $2
  fi
}

## Syntax: briefcase_set [key] [value]
function briefcase_set
{
  [ ! -f $HOME/.dotfiles/briefcase/settings.ini ] && touch $HOME/.dotfiles/briefcase/settings.ini
  if grep -q "^$1=" "$HOME/.dotfiles/briefcase/settings.ini"; then
    ESCAPED=$(echo $2 | sed -e 's/[]\/$*.^|[]/\\&/g')
    sed "s/^$1=.*/$1=$ESCAPED/" -i "$HOME/.dotfiles/briefcase/settings.ini"
  else
    echo "$1=$2" >> $HOME/.dotfiles/briefcase/settings.ini
  fi
}

## Syntax: briefcase_get [key]
function briefcase_get
{
  if [[ -f "$HOME/.dotfiles/briefcase/settings.ini" ]]; then
    RESULT=$(grep -oP "$1=\K.*" "$HOME/.dotfiles/briefcase/settings.ini")
    echo $RESULT || ""
  else
    echo ""
  fi
}

## Syntax: briefcase_git [repository] [name] [exec after update]
function briefcase_git
{
  if [ ! -d "$HOME/.source/$2" ]; then
    mkdir -p $HOME/.source/$2
    cd $HOME/.source/$2
    git clone $1 .
    eval $3
  else
    cd $HOME/.source/$2
    git fetch origin
    if [[ "$(git log HEAD..origin/master --oneline)" != "" ]]; then
      git merge origin/master
      eval $3
    fi
  fi
}
