#!/bin/bash

## Syntax: briefcase_symlink [source] [destination]
function briefcase_symlink
{
  if [ ! -d $1 ] && [ ! -f $1 ]; then
    echo "Error, the source ($1) does not exists"
    return
  fi

  if [ ! "$(readlink $2)" = "$1" ]; then
    if [ -d $2 ] || [ -f $2 ]; then
      echo "Warning! The destination file or folder already exists"
      echo "Moving $2 to $HOME/.dotfiles/briefcase/backup"
      read -p "Continue? (y/N)"
      [[ ! $REPLY =~ ^[Yy]$ ]] && return
      mv $2 $HOME/.dotfiles/briefcase/backup
    fi
   ln -s $1 $2
  fi
}

## Syntax: briefcase_set [file] [key] [value]
function briefcase_set
{
  [ ! -f $1 ] && touch $1
  if grep -q "^$2=" "$1"; then
    sed "s/^$2=.*/$2=$3/" -i $1
  else
    echo "$2=$3" >> $1
  fi
}

## Syntax: briefcase_get [file] [key]
function briefcase_get
{
  [ -f $1 ] && grep -oP ="$2=\K.*" $1
}

## Syntax: briefcase_git [repository] [name] [exec after update]
function briefcase_git
{
  if [ ! -d "$HOME/.source/$2" ]; then
    mkdir -p $HOME/.source/$2
    cd $HOME/.source/$2
    git clone $1 .
    eval $3
  else
    cd $HOME/.source/$2
    git fetch origin
    if [[ "$(git log HEAD..origin/master --oneline)" != "" ]]; then
      git merge origin/master
      eval $3
    fi
  fi
}
