#!/bin/bash

if [ -d "$HOME/.dotfiles" ]; then
  echo "It seems that the folder $HOME/.dotfiles already exists on your system."
  echo "Please rename, delete or move the .dotfiles folder and run this script again."
else
  git clone https://github.com/kevinvdburgt/dotfiles.git $HOME/.dotfiles
  source $HOME/.dotfiles/briefcase/sync
fi
