#!/usr/bin/env python3

import importlib
import platform
import os
import sys

from briefcase import Briefcase

if platform.system() == "Darwin":
    print("Detected OSX...")
    module = importlib.import_module('system.osx.system')
else:
    module = importlib.import_module('system.archlinux.system')	    
    #print("No machine detected...")
    #sys.exit()

getattr(module, 'System')(Briefcase())
