#!/usr/bin/env python

import platform
import os

from briefcase import Briefcase
from system.ArchLinux import SyncArchLinux
from system.OSX import SyncOSX

if platform.system() == "Linux" and os.path.isfile('/etc/arch-release'):
    print("Briefcase detected: Arch Linux")
    SyncArchLinux(Briefcase())
elif platform.system() == "Darwin":
    print("Briefcase detected: OSX")
    SyncOSX(Briefcase())
else:
    print("Briefcase detected: none, closing briefcasing..")
