#!/usr/bin/env python3

import importlib
import platform
import os
import sys

from briefcase import Briefcase

if platform.system() == "Linux":
    print("System platform: Linux")
    getattr(importlib.import_module('target.linux'), 'Target')(Briefcase())

if platform.system() == "Darwin":
    print("System platform: OSX")
    getattr(importlib.import_module('target.osx'), 'Target')(Briefcase())

else:
    print("No matching system platform found")
    sys.exit()
