#!/bin/bash

MONITORCOUNT=$1
OFFSET=' '

while read -r line; do
    case $line in
        DAT*) ## Time and date
            var_dat="${line#???}"
            ;;

        W*) ## BSPWM Internal State
            wminfo=("" "" "")
            currentMonitor=0
            bspwmMessage=${line#?}

            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ]; do
                item=$1
                name=${item#?}
                case $item in
                    [Mm]*) ## Curent monitor
                        currentMonitor="$name"
                        ;;
                    O*) ## Focused occupied monitor
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]}%{+u} ${name} %{-u}"
                        ;;
                    F*) ## Focused free desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]}%{+u} ${name} %{-u}"
                        ;;
                    U*) ## Focused urgent desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]}%{+u} ${name} %{-u}"
                        ;;
                    o*) ## Occupied desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]} ${name} "
                        ;;
                    f*) ## Free desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]} ${name} "
                        ;;
                    u*) ## Urgent desktop
                        wminfo[currentMonitor]="${wminfo[$currentMonitor]} ${name} "
                        ;;
                esac
                shift
            done
            ;;
    esac

    if [ $MONITORCOUNT -eq 1 ]; then
        ## Screen 1 (left)
        printf "%s" "%{S0}%{l}${OFFSET}"
        printf "%s" "${wminfo[0]}"

        ## Screen 1 (right)
        printf "%s" "%{S0}%{r}"
        printf "%s" " ${var_dat}"
    elif [ $MONITORCOUNT -eq 2 ]; then
        ## Screen 1 (left)
        printf "%s" "%{S0}%{l}${OFFSET}"
        printf "%s" "${wminfo[0]}"

        ## Screen 1 (right)
        printf "%s" "%{S0}%{r}"
        printf "%s" " ${var_dat}"

        ## Screen 2 (left)
        printf "%s" "${OFFSET}%{S1}%{l}${OFFSET}"
        printf "%s" "${wminfo[2]}"

        ## Screem 2 (right)
        printf "%s" "%{S1}%{r}"
        printf "%s" ""
    elif [ $MONITORCOUNT -eq 3 ]; then
        ## Screen 1 (left)
        printf "%s" "%{S0}%{l}${OFFSET}"
        printf "%s" "${wminfo[0]}"

        ## Screen 1 (right)
        printf "%s" "%{S0}%{r}"
        printf "%s" "R1"

        ## Screen 2 (left)
        printf "%s" "${OFFSET}%{S1}%{l}${OFFSET}"
        printf "%s" "${wminfo[2]}"

        ## Screem 2 (right)
        printf "%s" "%{S1}%{r}"
        printf "%s" "Email 0, 0, 0  |  "
        printf "%s" " ${var_dat}"

        ## Screen 3 (left)
        printf "%s" "${OFFSET}%{S2}%{l}${OFFSET}"
        printf "%s" "${wminfo[1]}"

        ## Screen 3 (right)
        printf "%s" "%{S2}%{r}"
        printf "R3"
    else
        printf "%s\n" "----[SORRY, NO SUPPORT FOR A DESKTOP WITH $MONITORCOUNT DESKTOPS]----"
    fi

    printf "%s\n" "${OFFSET}"
done
