#!/bin/bash

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=16
PANEL_FOREGROUND='#FFFFFFFF'
PANEL_BACKGROUND='#33FFFFFF'
PANEL_FONT='*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*,-benis-lemon-abunai-abunai-medium-r-normal--10-110-75-75-m-50-iso10646-1'
PANEL_MONITORCOUNT=$(bspc query -M | wc -l)

## Check if the panel script is already running.
if [ $(pgrep -cx panel) -gt 1 ]; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

## Trap the script
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

## Remove the fifo file if it exists, then create a new fifo file
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

## Tell the BSPC the padding and subscribe to the fifo file
bspc config top_padding $PANEL_HEIGHT &
bspc control --subscribe > "$PANEL_FIFO" &

## Send data to the fifo file
while true; do
    printf "%s%s\n" "DAT" "$(date +'%d-%m-%y %H:%M:%S')" > "$PANEL_FIFO"
    sleep 1s;
done &

cat "$PANEL_FIFO" | \
`dirname $0`/panel_bar $PANEL_MONITORCOUNT | \
bar \
    -g x$PANEL_HEIGHT \
    -F "$PANEL_FOREGROUND" \
    -B "$PANEL_BACKGROUND" \
    -f "$PANEL_FONT" -p

wait
