#!/bin/bash

# ----------------------------------------
# Sysupdate - Dotfiles updates
# 
# This is my dotfiles installation and
# upgrade script, keep in mind that this
# script is written for ArchLinux so it
# wont work on other distro's.
# ----------------------------------------

## 0. Check if the dotfiles are installed
if [ ! -d $HOME/.dotfiles/.git ]; then
  echo "Configuration file is missing."
  echo "Did you cloned the repository to \"$HOME/.dotfiles\" ?"
  exit
fi

## 1. Load the configuration which contains the
##    wallpaper, and other configs. Also load the
##    functions file
source $HOME/.dotfiles/dotsync/config
source $HOME/.dotfiles/dotsync/functions

## 2. Upgrade the system using pacman
read -p "Upgrade sysem packages using pacman (y/N)" -n 1 -r
echo
[[ $REPLY =~ ^[Yy]$ ]] && sudo pacman -Syu

## 3. Upgrade the system using yaourt
read -p "Upgrade sysem packages using yaourt (y/N)" -n 1 -r
echo
[[ $REPLY =~ ^[Yy]$ ]] && yaourt - Syua

## 4. Update applications directly from Git
read -p "Update and compile custom applications (y/N)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  dotfile_sourceupdate https://github.com/baskerville/bspwm.git bspwm bspwm bspc
  dotfile_sourceupdate https://github.com/baskerville/sxhkd.git sxhkd sxhkd
  dotfile_sourceupdate https://github.com/LemonBoy/bar.git bar bar
  dotfile_sourceupdate https://github.com/baskerville/xtitle.git xtitle xtitle
fi

## 5. Setup the symlinks
dotfile_symlink $HOME/.dotfiles/.config/bspwm/ $HOME/.config/bspwm
dotfile_symlink $HOME/.dotfiles/.config/gtk-3.0/ $HOME/.config/gtk-3.0
dotfile_symlink $HOME/.dotfiles/.config/sxhkd/ $HOME/.config/sxhkd
dotfile_symlink $HOME/.dotfiles/.config/compton.conf $HOME/.config/compton.conf

dotfile_symlink $HOME/.dotfiles/.fonts/ $HOME/.fonts
dotfile_symlink $HOME/.dotfiles/.scripts/ $HOME/.scripts

dotfile_symlink $HOME/.dotfiles/.weechat/weechat.conf $HOME/.weechat/weechat.conf

dotfile_symlink $HOME/.dotfiles/.Xresources $HOME/.Xresources
dotfile_symlink $HOME/.dotfiles/.bash_profile $HOME/.bash_profile
dotfile_symlink $HOME/.dotfiles/.gtkrc-2.0 $HOME/.gtkrc-2.0
dotfile_symlink $HOME/.dotfiles/.vimrc $HOME/.vimrc
dotfile_symlink $HOME/.dotfiles/.xinitrc $HOME/.xinitrc

## 6. Update the wallpaper
if [ ! "$(dotfile_get $DOTCONFIG_CONFIGFILE currentWallpaper)" = $DOTCONFIG_WALLPAPER ]; then
  echo "Downloading new wallpaper.."
  curl $DOTCONFIG_WALLPAPER -o $HOME/.config/wallpaper.png
  dotfile_set $DOTCONFIG_CONFIGFILE currentWallpaper $DOTCONFIG_WALLPAPER
fi

echo "----- [ SYSUPDATE / DOTSYNC COMPLETED ] -----"
