#!/usr/bin/env bash

# TODO: Move this back to the .xinitrc file?
sxhkd &

# TODO: Place this in a seperate folder where i can maintain machine settings
if [ "$(hostname)" == "blacklist" ]; then
    xrandr \
      --output DVI-D-0 \
      --mode 1920x1080 \
      --pos 3840x0 \
      --rotate right \
      --output HDMI-0 \
      --mode 1920x1080 \
      --pos 1920x275 \
      --rotate normal \
      --output DVI-I-1 \
      --mode 1920x1080 \
      --pos 0x275 \
      --rotate normal \
      --output DVI-I-0 \
      --off \
      --output DP-1 \
      --off --output \
      DP-0 --off
fi

# BSPWM behavior
bspc config border_width          3
bspc config split_ratio           0.52
bspc config window_gap            16
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true

# BSPWM colors
bspc config normal_border_color   "#2E2E2E"
bspc config active_border_color   "#5F5A60"
bspc config focused_border_color  "#1e1e1e"
bspc config urgent_border_color   "#FFFF00"
bspc config presel_feedback_color "#1e1e1e"

# BSPWM workspaces
for monitor in $(bspc query -M); do
  bspc monitor $monitor -d "One" "Two" "Three"
done

# BSPWM rules
#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# TODO: Move this to another script ?
#$HOME/.scripts/panel/panel &
#$HOME/.config/bspwm/lemonbar.sh
feh --bg-fill $HOME/.config/wallpaper.png &
compton --config $HOME/.config/compton.conf &
