#!/bin/bash

## Update system packages using pacman
sudo pacman -Syu

## Update system AUR packages using yaourt
#yaourt -Syua

## Download new dotfiles
cd $HOME/.dotfiles
git pull

## Run the briefcase updater
$HOME/.dotfiles/briefcase/sync

