#!/bin/bash

# ----------------------------------------
# Sysupdate - Dotfiles install / updates
# 
# This is my dotfiles installation and
# upgrade script, keep in mind that this
# script is written for ArchLinux so it
# wont work on other distro's.
# ----------------------------------------

## 0. Check if the dotfiles are installed
if [ ! -d $HOME/.dotfiles/.git ]; then
	echo "Configuration file is missing."
	echo "Did you cloned the repository to \"$HOME/.dotfiles\" ?"
	exit
fi

## 1. Update the dotfiles from the web
cd $HOME/.dotfiles
#git pull

## 2. run the dotfile updater
$HOME/.dotfiles/dotsync/update
exit


















CURRENTDIR=`pwd`
source $HOME/.dotfiles/config

# Update git source files and also make them
# Syntax: sourcefileupdate <gitrepo> <name> [fileA, fileB, ...]
function sourcefileupdate
{
	if [ ! -d "$HOME/.source/$2" ]; then
		mkdir $HOME/.source/$2 -p
		cd $HOME/.source/$2
		git clone $1 .
		make
		for FILE in "${@:3}"; do
			if [ -f $HOME/.source/$2/$FILE ]; then
				cp -u $HOME/.source/$2/$FILE $HOME/.bin
			fi
		done
	else
		cd $HOME/.source/$2
		git pull | tee /tmp/sourcefileupdate-log
		if ! grep -Fxq "Already up-to-date." "/tmp/sourcefileupdate-log"; then
			make
			for FILE in "${@:3}"; do
				if [ -f $HOME/.source/$2/$FILE ]; then
					cp -u $HOME/.source/$2/$FILE $HOME/.bin
				fi
			done
		fi
	fi
}

# Symlinking dotfiles
function symlinkDotfile
{
	echo "TODO: Create a symlink"
}

# Config, write setting
# Syntax: configWrite <file> <key> <value>
function configWrite
{
	# Create a new config file when it does not exists
	[ ! -f $1 ] && touch $1

	# Append or replace ?
	if grep -q "^$2=" "$1"; then
		sed "s/^$2=.*/$2=$3/" -i $1
	else
		echo "$2=$3" >> $1
	fi
}

# Config, read setting
# Syntax configRead <file> <key>
function configRead
{
	if [ -f $1 ]; then
		grep -oP "$2=\K.*" $1
	fi
}

# Update wallpaper
#echo '┌──────────────────────────────┐'
#echo '│ UPDATE WALLPAPER             │'
#echo '└──────────────────────────────┘'
#echo $CONFIG_SETTINGSFILE
#if [ "$(configRead $CONFIG_SETTINGSFILE currentWallpaper)" != "$CONFIG_WALLPAPER" ]; then
#    echo "Downloading new wallpaper..."
#    configWrite $CONFIG_SETTINGSFILE "currentWallpaper" "$CONFIG_WALLPAPER"
#else
#    echo "Wallpaper didnt changed"
#fi

# Update dotfiles
echo '┌──────────────────────────────┐'
echo '│ UPDATING DOTFILES            │'
echo '└──────────────────────────────┘'
if [ -d "$HOME/.dotfiles" ]; then
	cd $HOME/.dotfiles
	git pull
else
	mkdir $HOME/.dotfiles -p
	git clone https://github.com/kevinvdburgt/dotfiles.git $HOME/.dotfiles
fi

# Fixing symlinks
echo '┌──────────────────────────────┐'
echo '│ SYMLINKING DOTFILES          │'
echo '└──────────────────────────────┘'
symlinkDotfile .xinitrc $HOME
symlinkDotfile .vimrc $HOME
symlinkDotfile .gtkrc-2.0  $HOME
symlinkDotfile .bash_profile  $HOME
symlinkDotfile .Xresources $HOME
symlinkDotfile .scripts $HOME
symlinkDotfile .fonts $HOME
symlinkDotfile .config/compton.conf $HOME/.config/
symlinkDotfile .config/sxhkd/ $HOME/.config/
symlinkDotfile .config/ncmpcpp/ $HOME/.config/
symlinkDotfile .config/mpd/ $HOME/.config/
symlinkDotfile .config/gtk-3.0 $HOME/.config/
symlinkDotfile .config/bspwm $HOME/.config/

# System update
echo '┌──────────────────────────────┐'
echo '│ PACMAN                       │'
echo '└──────────────────────────────┘'
sudo pacman -Syu

# AUR update
echo '┌──────────────────────────────┐'
echo '│ YAOURT                       │'
echo '└──────────────────────────────┘'
yaourt -Syua

# .SOURCE applications
echo '┌──────────────────────────────┐'
echo '│ .SOURCE APPLICATIONS         │'
echo '└──────────────────────────────┘'
[ ! -d "$HOME/.source" ] && mkdir $HOME/.source -p
[ ! -d "$HOME/.bin" ] && mkdir $HOME/.bin -p
sourcefileupdate https://github.com/baskerville/bspwm.git bspwm bspwm bspc
sourcefileupdate https://github.com/baskerville/sxhkd.git sxhkd sxhkd
sourcefileupdate https://github.com/LemonBoy/bar.git bar bar
sourcefileupdate https://github.com/baskerville/xtitle.git xtitle xtitle
#sourcefileupdate https://github.com/wor/scrobby.git scrobby scrobby
