#!/bin/bash

# Create the screenshot
case $1 in
  # Create a screenshot by drawing a rectangle or clicking on a window
  select)
    scrot -q 100 -s /tmp/scrot.png
    ;;

  # Create a screenshot from all screens
  all)
    scrot -q 100 /tmp/scrot.png
    ;;

  # Display the screenshot usage
  *)
    echo $"Usage: $0 {select|all}"
    exit 1
    ;;
esac

# Upload the screenshot
RESPONSE=$(curl -sS -F "files[]=@/tmp/scrot.png" https://f.zdev.com/upload.php)

# @TODO: Check the upload status

# Fetch the uploaded file location
FILELOCATION=$(echo $RESPONSE | python2 -c 'import json,sys;obj=json.load(sys.stdin);print obj["files"][0]["url"]')
FILELOCATION="https://f.zdev.com/dl/$FILELOCATION"

# Put the filelocation in the clipboard
echo $FILELOCATION | xclip # Middlemouse clipboard
echo $FILELOCATION | xclip -selection c # CTRL+V clipboard
